version: "3.8"

services:
  back:
    build:
      context: ./backend-looksy
      dockerfile: Dockerfile
    image: back:fs1
    container_name: back_fs1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  front:
    build:
      context: ./frontend-looksy
      dockerfile: Dockerfile
    image: front:fs1
    container_name: front_fs1
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_API=http://sampablo.teclaguna.systems:3000/api
      - VITE_IMAGEN=http://sampablo.teclaguna.systems:3000
    depends_on:
      - back_fs1